### ISSUE TITLE
ItemNotFoundException

### ISSUE THREAD

**Issue by winjer** [awslabs/dynamodb-data-mapper-js#48]
`mapper.get` throws an `ItemNotFoundException` - except whatever it throws looks kind of broken:

```
     { Error
         at new ItemNotFoundException (/app/node_modules/@aws/dynamodb-data-mapper/build/ItemNotFoundException.js:12:28)
         at DataMapper.<anonymous> (/app/node_modules/@aws/dynamodb-data-mapper/build/DataMapper.js:659:31)
         at step (/app/node_modules/tslib/tslib.js:133:27)
         at Object.next (/app/node_modules/tslib/tslib.js:114:57)
         at fulfilled (/app/node_modules/tslib/tslib.js:104:62)
         at <anonymous>
         at process._tickCallback (internal/process/next_tick.js:160:7)
       itemSought:
        { TableName: 'charts',
          Key: { owner: [Object], fullname: [Object] },
          ConsistentRead: false } }
```

I suspect somewhere a function is being returned instead of called?

**Comment by winjer** [comment]
Sorry, I must have phrased my issue badly. It is correctly throwing an error but whatever it is that is thrown doesn't have a valid `code` or `message`. It does have `itemSought` added to it though.

It looks like there is a bug in the construction of the error somewhere.

**Comment by jeskew** [comment]
Understood; I can add a message derived from the `itemSought` property. 

The `ItemNotFoundException` constructor being included in the stack trace is an unfortunate side effect of prototypal inheritance -- the platforms that include a stack trace generate it from wherever `new Error` is called, which is when the direct child of `Error` calls `super();` in its constructor. V8 includes a utility function ([`Error.captureStackTrace`](https://nodejs.org/dist/latest-v8.x/docs/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt)) to work around this, but it can't be relied on across browsers.
