### ISSUE TITLE
Incompatible with AWS Lambda Node v8.10

### ISSUE THREAD

**Issue by denver-HJS** [awslabs/dynamodb-data-mapper-js#79]
Maybe I'm missing something, but I seem to be stuck between a rock and a hard place here.

I'm trying to handle a DynamoDB Stream event which requires a `batchGet` operation. This requires the experimental async iterator which has been creating issues when I deploy my handler.

If I only use the TypeScript compiler and polyfill then I get this error:

> Syntax error in module 'lib/functions/load-audience-trigger': SyntaxError
> for await (const audience of dataMapper.batchGet(mappedAudiences)) {
> ^^^^^
> 
> SyntaxError: Unexpected reserved word
> at createScript (vm.js:80:10)
> at Object.runInThisContext (vm.js:139:10)
> at Module._compile (module.js:616:28)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)

Since the `for await ... of` loop isn't officially supported yet and I can't execute the lambda with `--harmony_async_iteration` Node flag, I tried to downgrade to a Node v8.10 target using Babel. However this introduced a new problem where the experimental TS decorators used in the DDB entity classes cause the lambda to fail before it can even be imported:

> module initialization error
> Error

I assume this is a result of further manipulation by Babel after the TypeScript compiler has done it's work. However, without Babel I can't get beyond the syntax error generated around the `for await ... of` loop.

Are there any examples of how the data mapper can be used in the context of a DDB stream handler?

**Comment by jeskew** [comment]
I'm not familiar with Babel's TypeScript support, but the [mapper integration test](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-data-mapper/src/DataMapper.integ.ts) runs in Node 4+ when compiling with [this `tsconfig.json` file](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-data-mapper/tsconfig.json). 

Targeting `es5`, including the `esnext.asynciterable` lib, and enabling the `downlevelIteration` option will direct TypeScript to include a polyfill for async iteration.
