### ISSUE TITLE
Cannot store `Array<string>` in table

### ISSUE THREAD

**Issue by acheronfail** [awslabs/dynamodb-data-mapper-js#92]
I may have found a bug where I cannot store an `Array<string>` in the table. This is best explained with an example:

Here's my item definition:

```typescript
@table('items')
class Item {
  @hashKey()
  foo: string;

  @rangeKey()
  bar: string;

  @attribute({ memberType: 'String' })
  list: Array<string>;    // <--- this fails to be inserted/retrieved from db
}
```

And here's the test to reproduce:

```typescript
// Create the Dynamo client and DataMapper:
const client = new DynamoDB(config);
const dynamo = new DataMapper({ client });

// Ensure the table exists:
await dynamo.ensureTableExists(Item, { readCapacityUnits: 20, writeCapacityUnits: 10 });

// Create and add a generic item:
const item = Object.assign(new Item, {
  foo: 'foo',
  bar: 'bar',
  list: ['list', 'of', 'strings']
});
await dynamo.put(item);  // <--- error occurs here

// Scan the db for all items:
for await (const item of dynamo.scan(Item)) {
  console.log('scanning table:', item);
}
```
Which, results in the following error:

```text
Error: Unrecognized schema node
  at new InvalidSchemaError (/var/service/node_modules/@aws/dynamodb-data-marshaller/src/InvalidSchemaError.ts:9:9)
  at marshallValue (/var/service/node_modules/@aws/dynamodb-data-marshaller/src/marshallItem.ts:258:11)
  at marshallValue (/var/service/node_modules/@aws/dynamodb-data-marshaller/src/marshallItem.ts:139:32)
  at Object.marshallItem (/var/service/node_modules/@aws/dynamodb-data-marshaller/src/marshallItem.ts:29:33)
  at DataMapper.<anonymous> (/var/service/node_modules/@aws/dynamodb-data-mapper/src/DataMapper.ts:661:19)
  at step (/var/service/node_modules/tslib/tslib.js:133:27)
  at Object.next (/var/service/node_modules/tslib/tslib.js:114:57)
  at /var/service/node_modules/tslib/tslib.js:107:75
  at new Promise (<anonymous>)
  at Object.__awaiter (/var/service/node_modules/tslib/tslib.js:103:16)
node: 'String'
```

I would expect that the `item.list` property is stored as a `List` type ([see here for the `List` type](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes)). But instead, it throws saying that the schema is unrecognised.

It's worth noting that using a `Set<string>` solves the problem, but then the item isn't stored as a list.

Is this intended behaviour, or is this a bug?

**Comment by jeskew** [comment]
Hi @acheronfail,

There is a slight difference between how you configure the member type for sets (which can only contain all strings, all numbers, or all binary blobs) and lists (which can contain elements of any type). Because lists can contain aggregate types, any mixture of types, or no types, it is represented in the data mapper's schema ontology by three types: `List`s, which contain any number of elements of a given type; `Tuple`s, which contain a fixed number of elements of known types; and `Collection`s, which contain any number of elements of any type.

For a list of strings, you would want to do the following:

```typescript
@attribute({ memberType: {type: 'String' }})
list: Array<string>;
```

Because the `memberType` of a `List` can be an aggregate type (e.g., a `List` of `List`s of `string`s), its member type is a full schema node rather than just a string.

**Comment by jamalumusic** [comment]
This can be handle for .ts file but what about the .js file.

```Object.defineProperties(EverBridgePosts.prototype, {
    [DynamoDbTable]: {
        value: 'EverBridgeNotifications'
    },
    [DynamoDbSchema]: {
        value: {
            EverBridgeId: {
                type: 'String',
                keyType: 'HASH',
                defaultProvider: v4,
            },
            createdAt: {
	              type: 'Date',
	              keyType: 'RANGE'
            },
            authorUsername: {type: 'String'},
            title: {type: 'String'},
            sitecode:{type:'Array<any>'}, // Here am  getting error...
            metadata: embed(EverBridgePostMetadata)
        },
    },
});


(node:32234) UnhandledPromiseRejectionWarning: Error: Unrecognized schema node
    at new InvalidSchemaError (/Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/@aws/dynamodb-data-marshaller/src/InvalidSchemaError.ts:9:9)
    at marshallValue (/Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/@aws/dynamodb-data-marshaller/src/marshallItem.ts:258:11)
    at Object.marshallItem (/Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/@aws/dynamodb-data-marshaller/src/marshallItem.ts:29:33)
    at DataMapper.<anonymous> (/Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/@aws/dynamodb-data-mapper/src/DataMapper.ts:661:19)
    at step (/Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/tslib/tslib.js:117:57)
    at /Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/tslib/tslib.js:106:16)
    at DataMapper.put (/Users/abduljamal/Documents/mywork/api/umgc-everBridge_api/node_modules/@aws/dynamodb-data-mapper/build/DataMapper.js:678:24)
(node:32234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
